label: "Elasticsearch"
priority: 3

ils_adapter:
  class: !ruby/class "Fahrenheit::AlephUbpb::Adapter"
  name: "Aleph"
  options:
    default_document_base: "PAD01"
    default_user_library: "PAD50"
    restful_api_url: "http://ubex.uni-paderborn.de:1891/rest-dlf"
    x_services_url: "https://ubex.uni-paderborn.de/X"

search_engine_adapter:
  class: !ruby/class "Celsius::Elasticsearch::Adapter"
  options:
    hosts:
      - host: "ubstage1"
    facets_via_aggregations: true
    index: catalog

defaults:
  facets:
    __aggregatable.creator:
      terms:
        field: "__aggregatable.creator"
        shard_size: 75

    __aggregatable.subject:
      terms:
        field: "__aggregatable.subject"
        shard_size: 75

    __aggregatable.classification:
      terms:
        field: "__aggregatable.classification"
        shard_size: 75

  search_request:
    from: 0
    size: 20
    sort:
    - _score

searchable_fields:
  - _all
  - "__searchable.creator"
  - "__searchable.title"
  - "__searchable.subject"
  - "__searchable.identifier"

sortable_fields:
  - _score
