label: "Elasticsearch"
priority: 3

search_engine_adapter:
  class: !ruby/class "Celsius::Elasticsearch::Adapter"
  options:
    hosts:
      - host: "192.168.1.50"
    facets_via_aggregations: true
    index: catalog

defaults:
  search_request:
    facets:
      __aggregatable.classification:
        terms:
          field: "__aggregatable.classification"
          shard_size: 75

      __aggregatable.creator:
        terms:
          field: "__aggregatable.creator"
          shard_size: 75

      __aggregatable.subject:
        terms:
          field: "__aggregatable.subject"
          shard_size: 75

    from: 0
    size: 20
    sort:
    - _score

searchable_fields:
  - _all
  - "__searchable.creator"
  - "__searchable.title"
  - "__searchable.subject"
  - "__searchable.identifier"

sortable_fields:
  - _score
