common_settings: &common_settings
  ils_adapter:
    ubpb_aleph_adapter:
      class_name: "KatalogUbpb::UbpbAlephAdapter"
      options:
        default_document_base: "PAD01"
        default_user_library: "PAD50"
        restful_api_url: "http://ubtest.uni-paderborn.de:1891/rest-dlf"
        x_services_url: "https://ubtest.uni-paderborn.de/X"
      scope: "local"

  search_engine_adapter:
    ubpb_elasticsearch_adapter:
      class_name: "KatalogUbpb::UbpbElasticsearchAdapter"
      options:
        hosts:
          - host: "ubstage1"
        index: katalog

  scopes:
    local:
      ils_adapter: "ubpb_aleph_adapter"
      search_engine_adapter: "ubpb_elasticsearch_adapter"
      facets:
        - name: "materialtypen"
          type: "terms"
          field: "materialtyp_facet"
          i18n_key: "materialtypen"
        - name: "creators"
          type: "terms"
          field: "creator_contributor_facet"
        - name: "erscheinungsformen"
          type: "terms"
          field: "erscheinungsform_facet"
          i18n_key: "erscheinungsformen"
        - name: "subjects"
          type: "terms"
          field: "subject_facet"
        - name: "creation_dates"
          type: "histogram"
          field: "creationdate_facet"
        - name: "languages"
          type: "terms"
          field: "language_facet"
          i18n_key: "languages"
        - name: "notations"
          type: "terms"
          field: "notation_facet"
        - name: "inhaltstypen"
          type: "terms"
          field: "inhaltstyp_facet"
          i18n_key: "inhaltstypen"

        #- name: "neuerwerbungen"
        #  type: "range"
        #  field: "cataloging_date"
        #  ranges:
        #    - from: "now-1M"
        #      key: "last_month"
        #    - from: "now-3M"
        #      key: "last_three_months"
        #    - from: "now-6M"
        #      key: "last_six_months"

      searchable_fields:
        - "_all"
        - "creator_contributor_search"
        - "title_search"
        - "subject_search"
        - "publisher"
        - "toc"
        - "creationdate_search"
        - "isbn_search"
        - "issn"
        - "signature_search"
        - "notation"
        - "ht_number"
        - "superorder"

      sortable_fields:
        - creator_contributor_facet
        - creationdate_facet: asc
        - creationdate_facet: desc
        - _score
        - notation_sort
        - title_sort
        - volume_count_sort: asc
        - volume_count_sort: desc

development: &development
  <<: *common_settings

test:
  <<: *development

production:
 <<: *common_settings
