common_settings: &common_settings
  ils_adapter:
    class_name: "KatalogUbpb::UbpbAlephAdapter"
    options:
      default_document_base: "PAD01"
      default_user_library: "PAD50"
      restful_api_url: "http://ubtest.uni-paderborn.de:1891/rest-dlf"
      x_services_url: "https://ubtest.uni-paderborn.de/X"
      #source_id: "PAD_ALEPH"

  search_scopes:
    local:
      search_engine_adapter:
        class_name: "KatalogUbpb::UbpbElasticsearchAdapter"
        options:
          hosts:
            - host: "ubstage1.uni-paderborn.de"
          facets_via_aggregations: true
          index: katalog

      facets:
        - name: "creator"
          type: "terms"
          field: "creator_contributor_facet"

        - name: "erscheinungsform"
          type: "terms"
          field: "erscheinungsform"

      searchable_fields:
        - "_all"
        - "creator_contributor_search"
        - "title_search"
        - "subject_search"
        - "publisher"
        - "toc"
        - "creationdate_search"
        - "isbn"
        - "issn"
        - "signature_search"
        - "notation"
        - "ht_number"

      sortable_fields:
        - "_score"
        - "short_title_display"

development: &development
  <<: *common_settings

test:
  <<: *development

production:
 <<: *common_settings
