common_settings: &common_settings
  ils_adapter:
    class_name: "KatalogUbpb::UbpbAlephAdapter"
    options:
      default_document_base: "PAD01"
      default_user_library: "PAD50"
      restful_api_url: "http://ubtest.uni-paderborn.de:1891/rest-dlf"
      x_services_url: "https://ubtest.uni-paderborn.de/X"

  search_scopes:
    local:
      search_engine_adapter:
        class_name: "KatalogUbpb::UbpbElasticsearchAdapter"
        options:
          hosts:
            - host: "localhost"
          facets_via_aggregations: true
          index: katalog

      facets:
        - name: "creators"
          type: "terms"
          field: "creator_contributor_facet"
        - name: "erscheinungsformen"
          type: "terms"
          field: "erscheinungsform"
          i18n_key: "erscheinungsformen"
        - name: "subjects"
          type: "terms"
          field: "subject_facet"
        - name: "creation_dates"
          type: "histogram"
          field: "creationdate_facet"
        - name: "languages"
          type: "terms"
          field: "language"
          i18n_key: "languages"
        - name: "notations"
          type: "terms"
          field: "notation"
        - name: "inhaltstypen"
          type: "terms"
          field: "inhaltstyp"
          i18n_key: "inhaltstypen"
        - name: "materialtypen"
          type: "terms"
          field: "materialtyp"
          i18n_key: "materialtypen"

        #- name: "neuerwerbungen"
        #  type: "range"
        #  field: "cataloging_date"
        #  ranges:
        #    - from: "now-1M"
        #      key: "last_month"
        #    - from: "now-3M"
        #      key: "last_three_months"
        #    - from: "now-6M"
        #      key: "last_six_months"

      searchable_fields:
        - "_all"
        - "creator_contributor_search"
        - "title_search"
        - "subject_search"
        - "publisher"
        - "toc"
        - "creationdate_search"
        - "isbn"
        - "issn"
        - "signature_search"
        - "notation"
        - "ht_number"

      sortable_fields:
        - "_score"
        - "short_title_display"

development: &development
  <<: *common_settings

test:
  <<: *development

production:
 <<: *common_settings
